server:
  port: 8002
spring: 
  profiles: 
    active: dev
---
spring: 
  profiles: dev
server: 
  port: 8008
--- 
spring: 
  profiles: test
server: 
  port: 8009
---
spring: 
  profiles: prod
server: 
  port: 8010
